const ReservationActionsTypes = {
    CREATE_RESERVATION_START: 'CREATE_RESERVATION_START',
    CREATE_RESERVATION_SUCCESS: 'CREATE_RESERVATION_SUCCESS',

    UPDATE_RESERVATION_START: 'UPDATE_RESERVATION_START',
    UPDATE_RESERVATION_SUCCESS: 'UPDATE_RESERVATION_START',

    DELETE_RESERVATION_START: 'DELETE_RESERVATION_START',
    DELETE_RESERVATION_SUCCESS: 'DELETE_RESERVATION_SUCCESS',

    GET_RESERVATIONS_START: 'GET_RESERVATIONS_START',
    GET_RESERVATIONS_SUCCESS: 'GET_RESERVATIONS_SUCCESS',

    GET_RESERVATIONS_REPORT_START: 'GET_RESERVATIONS_REPORT_START',
    GET_RESERVATIONS_REPORT_SUCCESS: 'GET_RESERVATIONS_REPORT_SUCCESS',

    RESERVATION_BACKEND_ERROR: 'RESERVATION_BACKEND_ERROR'
};

export default ReservationActionsTypes;