const TableActionsTypes = {
    CREATE_TABLE_START: 'CREATE_TABLE_START',
    CREATE_TABLE_SUCCESS: 'CREATE_TABLE_SUCCESS',

    UPDATE_TABLE_START: 'UPDATE_TABLE_START',
    UPDATE_TABLE_SUCCESS: 'UPDATE_TABLE_SUCCESS',

    DELETE_TABLE_START: 'DELETE_TABLE_START',
    DELETE_TABLE_SUCCESS: 'DELETE_TABLE_SUCCESS',

    GET_TABLES_SUCCESS: 'GET_TABLES_SUCCESS',

    TABLE_BACKEND_ERROR: 'TABLE_BACKEND_ERROR'
};

export default TableActionsTypes;