const UserActionTypes = {
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_IN_START: 'SIGN_IN_START',

    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_OR_UP_FAILURE: 'SIGN_IN_OR_UP_FAILURE',

    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

    SET_RESTAURANT_NAME_START: 'SET_RESTAURANT_NAME_START',
    SET_RESTAURANT_NAME_SUCCESS: 'SET_RESTAURANT_NAME_SUCCESS',

    USER_BACKEND_ERROR: 'USER_BACKEND_ERROR'
};

export default UserActionTypes;
