const UserActionTypes = {
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

    SIGN_IN_OR_UP_FAILURE: 'SIGN_IN_OR_UP_FAILURE',
};

export default UserActionTypes;
