const UserActionTypes = {
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_IN_START: 'SIGN_IN_START',

    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_OR_UP_FAILURE: 'SIGN_IN_OR_UP_FAILURE',

    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
};

export default UserActionTypes;
